# Generated by Django 3.2.3 on 2021-06-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/media/profile_pics/default.jpg/', upload_to='profile_pics/'),
        ),
    ]
