# Generated by Django 3.2.3 on 2021-06-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0009_customuser_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_online',
        ),
    ]
